version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cubes_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: cubes_db
      POSTGRES_USER: cubes_user
      POSTGRES_PASSWORD: cubes_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    ports:
      - "5433:5432"
    networks:
      - cubes_network_dev

  # Backend API (Development)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: cubes_api_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5001
      DATABASE_URL: postgresql://cubes_user:cubes_password@postgres:5432/cubes_db
      FRONTEND_URL: http://localhost:3002
      CORS_ORIGIN: http://localhost:3002
      CLICKHOUSE_HOST: http://clickhouse:8123
      CLICKHOUSE_USER: analytics_user
      CLICKHOUSE_PASSWORD: analytics_password
      CLICKHOUSE_DATABASE: analytics
    ports:
      - "5001:5001"
    volumes:
      - ./backend/src:/app/src:ro
    networks:
      - cubes_network_dev
    depends_on:
      - postgres
      - clickhouse

  # Frontend (Development - served by Vite dev server)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cubes_frontend_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - "3002:3002"  # Vite dev server with HTTPS
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    networks:
      - cubes_network_dev
    depends_on:
      - backend

  # ClickHouse Analytics Database
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: cubes_analytics_dev
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: analytics_user
      CLICKHOUSE_PASSWORD: analytics_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # TCP interface
    volumes:
      - clickhouse_data_dev:/var/lib/clickhouse
      - ./analytics/config.xml:/etc/clickhouse-server/config.d/custom.xml:ro
      - ./analytics/users.xml:/etc/clickhouse-server/users.d/custom.xml:ro
      - ./analytics/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cubes_network_dev
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # Traffic Simulator
  traffic-simulator:
    build:
      context: ./traffic-simulator
      dockerfile: Dockerfile
    container_name: cubes_traffic_simulator_dev
    restart: unless-stopped
    environment:
      CONCURRENT_BROWSERS: 10
      SESSION_DURATION_MIN: 15
      SESSION_DURATION_MAX: 45
      TARGET_URL: http://frontend:3002
      RESTART_DELAY: 1000
      LOG_LEVEL: info
      NODE_ENV: development
    volumes:
      - ./traffic-simulator/logs:/app/logs
    networks:
      - cubes_network_dev
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  postgres_data_dev:
    driver: local
  clickhouse_data_dev:
    driver: local

networks:
  cubes_network_dev:
    driver: bridge
    name: cubes_network_dev